### ISSUE TITLE
Publish html version of the spec

### ISSUE THREAD

**Issue by dbuenzli** [devicetree-org/devicetree-specification#10]
It would be nice to publish an html version of the spec on the website at a stable, versioned, url (`make html` seems to work quite well). This is useful for cross referencing specific sections of the spec from other documents and for general online discussion; something that is less easy to do on PDF documents.

**Comment by glikely** [comment]
Unofficial stable and latest version of HTML documentation are now published on readthedocs:

http://devicetree-specification.readthedocs.io/en/latest/

**Comment by dbuenzli** [comment]
Thanks ! Very nice.
