### ISSUE TITLE
Add document version information to readthedoc.io HTML output

### ISSUE THREAD

**Issue by glikely** [devicetree-org/devicetree-specification#13]
The HTML version of the document published on readthedocs.io doesn't show any information about the document version. There needs to be a clear banner to show when it is an unreleased version of the document.

http://devicetree-specification.readthedocs.io/en/latest/

There is no issue with the PDF copy on readthedocs.io because it already has a watermark showing the git commit id.

**Comment by lurch** [comment]
It would also be great if that RTD link was provided somewhere in this project's README or somewhere on devicetree.org!

Currently https://www.devicetree.org/specifications/ just links to https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.3-rc1 and IMHO it's a bit user-unfriendly to only offer a source code zipfile :slightly_frowning_face:

**Comment by robherring** [comment]
It is source only because the PDF building is broken on v0.3-rc1 and I
haven't investigated why.

**Comment by lurch** [comment]
> the PDF building is broken on v0.3-rc1 and I haven't investigated why

Just out of curiosity, I decided to take a quick look... seems like one (or more?) of the Sphinx requirements now needs at least Python3.5 (I did this by creating a virtualenv). And in Python 3, [subprocess.check_output](https://docs.python.org/3/library/subprocess.html#subprocess.check_output) returns bytes by default, which lead to an exception on line 259 of `conf.py`. So I fixed that by adding the `universal_newlines=True` parameter to line 69 of `source/conf.py`, and after doing that `make latexpdf` works fine, and I get a `build/latex/devicetree-specification.pdf` (which seems to be okay AFAICT).

**Comment by robherring** [comment]
Adding the version in the html output is done. A problem with RTD output remains. It will probably work if a tag is pushed before a branch with the tag is. A branch push doesn't find a version likely because a shallow clone is done. Pushing a tag afterwards doesn't work because RTD thinks it already built that version. @glikely will have to fix the RTD side.

Note that GH Pages works fine: http://devicetree-org.github.io/devicetree-specification/
