### ISSUE TITLE
Outdated README link to specification

### ISSUE THREAD

**Issue by lurch** [devicetree-org/devicetree-specification#26]
The README links to https://github.com/devicetree-org/devicetree-specification-released

However GitHub tells me "This repository has been archived by the owner. It is now read-only." :confused: 
It also only contains version 0.1, whereas https://github.com/devicetree-org/devicetree-specification/releases says versions 0.2 and 0.3rc1 now exist!

**Comment by robherring** [comment]
Fixed in commit a13d0e0b8478.
