### ISSUE TITLE
MIME type for DeviceTree dts files

### ISSUE THREAD

**Issue by scop** [devicetree-org/devicetree-specification#46]
We got a request to resolve a problem where `*.dts` files are associated with (only) DTS audio in the shared-mime-info database: https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/173

DTS audio is properly registered in the IANA media types registry with the `*.dts` extension: https://www.iana.org/assignments/media-types/audio/vnd.dts

The only doc I was able to find related to DeviceTree media types is https://pygments.org/docs/lexers/#lexers-for-devicetree-language but associating `*.dts` with a C source code media type would likely be a source for problems.

Do you have a suggestion or a ready specification that would tell the media type to use with these DeviceTree files?

**Comment by StefanBruens** [comment]
The actual content is a strict 'printable ascii' subset, i.e. CR, LF, TAB, and printable characters (0x20-0x7e).

Comments may contain UTF-8, though this is not mentioned in the spec. Every comments starts with the two characters "/*" or "//".

The file may have a UTF-8 BOM, though this is also not covered in the spec. BOMs are discouraged for UTF-8, as not necessary.


As the first four bytes of DTS Audio are all non-ASCII characters, this should be sufficient to detect device-tree-source files.

Nevertheless, mime-types should be registered (also for DTSI and DTB).

**Comment by robherring** [comment]
Nothing concrete to do here, closing.

**Comment by robherring** [comment]
@StefanBruens That's not something I can fix in the spec which is what this repo is for. As for how to handle MIME types, I don't have a clue how or where.

**Comment by StefanBruens** [comment]
As you are a representative for the DTS format, you are likely a good choice for filing a MIME type registration request, shouldn't take more than 10 minutes:
https://www.iana.org/form/media-types
