### ISSUE TITLE
Invalid MAC address in example

### ISSUE THREAD

**Issue by JaapKeuter** [devicetree-org/devicetree-specification#47]
"Table 4.9: mac-address Property" contains an example for the use of this property:

`mac-address = [ 01 02 03 04 05 06 ];`

This MAC address is a group address, therefore cannot be used as source address. <br>
Please replace the `01` by a even value, e.g.:

`mac-address = [ 02 03 04 05 06 07 ];`

which constitutes a locally administered address.

**Comment by robherring** [comment]
Can you make a PR or patch to fix it.
