### ISSUE TITLE
This repo has both master and main branches

### ISSUE THREAD

**Issue by wmamills** [devicetree-org/devicetree-specification#54]
This repo has both master and main branches.  The main branch is ahead of master by 2 commits.
This is very confusing.
The master branch should be deleted to avoid confusion.
If the github rename master function is used [1] then support for a master alias is done.
My understanding is:
* make master and main in sync
* delete main
* rename master to main using github control panel as described below

[1] https://github.com/github/renaming

**Comment by robherring** [comment]
Out of sync is because I forgot... I didn't realize a GH rename will alias it, though it is not clear to me if the redirect works for git CLI or just the web?

**Comment by wmamills** [comment]
I have previously tested on the CLI and found it working for my test repos.
It won't rename a branch in a repo already cloned but it will allow that clone to continue to pull.
I THINK it creates a symlink ref much like HEAD is.

**Comment by robherring** [comment]
Both branches have existed for some time now. So I've deleted the 'master' branch now.
