### ISSUE TITLE
Generic node name for vibration motor / haptics

### ISSUE THREAD

**Issue by z3ntu** [devicetree-org/devicetree-specification#58]
Hi, there are increasingly kernel drivers for vibration motors added for phones and similar devices. In mainline Linux `vibrator`, `haptics` and `haptic-feedback` (and maybe more?) is used so it's probably a good idea to standardize a name in the devicetree spec.

`vibrator` is currently used 19 times, `haptics` 3 times and `haptic-feedback` 4 times.

I'd be happy to submit a PR adding this to the spec but I'm not sure which of the names is preferred - or even a completely different one.

**Comment by robherring** [comment]
Go with vibrator as that seems to be most common.
