### ISSUE TITLE
Property inheritance

### ISSUE THREAD

**Issue by andreiw** [devicetree-org/devicetree-specification#72]
Should something in the spec explicitly say properties are never inherited?

2.3.5 says "The #address-cells and #size-cells properties are not inherited from ancestors in the device tree. They shall be explicitly defined", but that makes it sound like /some/ properties could be inherited.

**Comment by robherring** [comment]
I believe this came from cases where those properties did get inherited. There's still remnants of default root cell sizes in the tools and kernel (they don't even agree).

If there's a way you thing the wording can be improved please propose a change. Otherwise this issue will just sit here.

**Comment by andreiw** [comment]
Sure I think I can propose an improvement. But we do agree that properties never do get inherited, right?

**Comment by robherring** [comment]
Now that I think about, there is a case and the spec even says so IIRC. 'cpu' properties can be in 'cpus' node instead if the property is the same for all CPUs.

**Comment by CodingVoid** [comment]
> The #address-cells and #size-cells properties are not inherited from ancestors in the device tree. They shall be explicitly defined"

Linux devicetree implementation seems to treat both as inheritable as far as I can see:
https://github.com/torvalds/linux/blob/fe46a7dd189e25604716c03576d05ac8a5209743/drivers/of/base.c#L89

**Comment by robherring** [comment]
> > The #address-cells and #size-cells properties are not inherited from ancestors in the device tree. They shall be explicitly defined"
> 
> Linux devicetree implementation seems to treat both as inheritable as far as I can see: https://github.com/torvalds/linux/blob/fe46a7dd189e25604716c03576d05ac8a5209743/drivers/of/base.c#L89

The kernel has to work with OpenFirmware platforms going back to the 1990s, so yes it is more lax than what is defined for FDT.

**Comment by robherring** [comment]
Also note that relying on defaults has been a warning in dtc since 2007:

commit 7e089d9473989bc6dadfdfa81fa3fc029abf26db
Author: David Gibson <david@gibson.dropbear.id.au>
Date:   Fri Dec 7 14:05:55 2007 +1100

    dtc: Convert #address-cells and #size-cells related checks
    
    This patch converts checks related to #address-cells and #size-cells
    to the new framework.  Specifically, it reimplements the check that
    "reg" properties have a valid size based on the relevant
    #address-cells and #size-cells values.  The new implementation uses
    the correct default value, unlike the old-style check which assumed
    the values were inherited by default.
    
    It also implements a new, similar test for "ranges" properties.
    
    Finally, since relying on the default values of these variables is
    considered not-good-practice these days, it implements a "style" check
    which will give a warning if the tree ever relies on the default
    values (that is if any node with either "reg" or "ranges" appears
    under a parent which has no #address-cells or #size-cells property).

**Comment by robherring** [comment]
Make a proposed change if you still feel the spec should be reworded.
