### ISSUE TITLE
Usage of EfiReservedMemoryType

### ISSUE THREAD

**Issue by xypron** [devicetree-org/devicetree-specification#74]
We require that memory ranges defined in sub-nodes of /reserved-memory are

* EfiReservedMemoryType if the range has the no-map property.
* EfiBootServicesData otherwise.

We require the usage of EfiReservedMemoryType for regions defined in the Memory Reservation Block.

The description in 5.3, "Memory Reservation Block" makes it clear that regions in the Memory Reservation Block may be mapped:

"More specifically, a client program shall not access memory in a reserved region unless other information provided by
the boot program explicitly indicates that it shall do so."

This implies that the operating system cannot deduct which memory regions may be mapped by looking only at the EFI memory map. It might be preferable to use EfiBootServicesData for the  Memory Reservation Block as it is not meant to use the no-map semantics.

**Comment by robherring** [comment]
I would suggest you raise your issue on boot-architecture@lists.linaro.org maillist. This is not a DT spec issue.
