### ISSUE TITLE
example does not compile

### ISSUE THREAD

**Issue by orangecms** [devicetree-org/devicetree-specification#75]
Hello :) 

I tried to compile this example:

https://github.com/devicetree-org/devicetree-specification/blob/2697c66a59b9177f8ff7813c355cc7aa05f6e40a/source/chapter2-devicetree-basics.rst?plain=1#L1249-L1279

saved it as `int-example.dts` and ran

```sh
dtc int-example.dts -o int-example.dtb 
````

I had to make 3 changes for it to compile:
- add the DT version declaration and outer `{` / `};`
- rename `open-pic` to `open_pic` to be syntactically valid
- add a name@addr to `open_pic`, because dtc otherwise says it cannot be found, e.g. `open_pic: interrupt-controller@13370000`

Am I holding this wrong, or is this really not working? I'll gladly file a PR to adjust it.

**Comment by robherring** [comment]
I agree the last 2 items should be fixed. I don't think examples need to be a complete dts though.
