### ISSUE TITLE
Feature Request: Arithmetic operations for better readability?

### ISSUE THREAD

**Issue by Kreyren** [devicetree-org/devicetree-specification#77]
```diff
vdda_ebi0_1:
vdda_ebi0_2:
vreg_s1a_0p8: smps1 {
-	regulator-min-microvolt = <800000>; // 0.8V = 800 000 microvolts
+   regulator-min-microvolt = <0.8 * 1 000 000>;
-	regulator-max-microvolt = <4400000>; // 4.4V (80% of 5.5V) = 4 400 000 microvolts
+   regulator-max-microvolt = <4.4 * 1 000 000>; // 80% of 5.5V
}
```

**Comment by robherring** [comment]
Math operations are already supported, but only for integers as floats are not supported in DTS. If you want to add floating point, there are some patches in the Asahi Linux project doing that for dtc.

In any case, the only way this will get added is if you or someone does the work to add it to dtc (first) and the spec. devicetree-compiler@vger.kernel.org list is where that happens.
