### ISSUE TITLE
Memory reservation block: clarify size unit of memory reserved regions

### ISSUE THREAD

**Issue by dbuenzli** [devicetree-org/devicetree-specification#9]
On p. 40 it is said: 

```
Each pair gives the physical address and size of a reserved memory region. 
```

It is unclear whether the `size` field unit is words or bytes.

**Comment by dbuenzli** [comment]
Similarly on p. 39. the unit of `totalsize` is undefined (given the other fields I assume this is in bytes).

**Comment by robherring** [comment]
Send patches please, not github issues.

**Comment by dbuenzli** [comment]
I can't do PRs for something I'm not unsure about the answer but if you mean this should reported to the list then maybe this should be clarified on the website.

**Comment by glikely** [comment]
Picking up on this topic. I don't have a problem with raising issue on github. In a lot of cases that may be the best way for us to get "drive-by" feedback. In this case, I've gone and looked at the document and I'm about to post a patch to fix it. However, I do agree that any final resolution/patch needs to hit the mailing list before it is committed to the document.
